### PR TITLE
IE App for Industrial Edge Release V1.2

### PR DESCRIPTION
**Pull request by Chris1612**

### CODE REVIEW

**Comment by EndyCZ** [comment]
Perfect. Just this last one still contains the configuration flows.

https://github.com/Chris1612/Developer-Guide-Hands-on-App/blob/master/src/solution/node_red/node-red/flows.json

**Comment by EndyCZ** [comment]
Please add the comment to tell user that he needs to wait for first 50 values before anything is showved in the grafana graph

**Comment by Chris1612** [comment]
Added comments to the Data Collection and Generation flow

- wait for 50 values before grafana shows data
- How to configure databus security

**Review by EndyCZ — CHANGES_REQUESTED** [review]
Somehow when I restart the docker-compose for nodered I still get all the configuration nodes.
Please delete them. It is probably in this file problem. 
src/solution/node_red/node-red/flows.json

**Comment by Chris1612** [comment]
I formated the flows so that the flow is directly visible

**Review by EndyCZ — APPROVED** [review]
great

**Pull request merged**
