### PR TITLE
Developer Guide 2.0

### PR DESCRIPTION
**Pull request by EndyCZ**
* Updated all the open source software (Grafana, InfluxDB, NodeRed)
* Changed NodeRed flows due to software update
* Add additional security aspect in docker-compose.yml: Linux capabilities, read-only file system, non-root user, container initialization
* Add tracee
* Delete MQTT external networks in docker-compose
* Separate basic example and security extension into HandsOn_1 and HandsOn_2 folder
* Add Demo OPCUA Server Simulator and add OPCUA Client Flows in NodeRED

Co-authored-by: Si Hao Shen <si-hao.shen@siemens.com>
Co-authored-by: Ondrej Havlicek <ondrej-havlicek@siemens.com>
Co-authored-by: Daniel Stus <daniel.stus@siemens.com>

See Pull request #13 for details.

### CODE REVIEW

**Comment by EndyCZ** [comment]
this should fix #16

**Comment by EndyCZ** [comment]
I found that adding he testtoken to configure nodered password is not enough. I guess you tested it with different version of NodeRED. 

I think you should include also the lockfile (lock.json) and not just package.json in the NodeRed repository to avoid these problems in the future.

**Comment by EndyCZ** [comment]
> 

my bad, I had some old images in my dev enviroment. It works fine.

**Comment by EndyCZ** [comment]
This flow uses outdated config for MQTT nodes. https://github.com/industrial-edge/Developer-Guide-Hands-on-App/blob/devguide-1.5-wip/src/solution/HandsOn_2/IE%20Flow%20Creator%20Flows/flow_data_S7_Connector.json

**Comment by EndyCZ** [comment]
@StushaaK  @HummelN7872  Everything should be finished. Developer guide is already released. https://docs.eu1.edge.siemens.cloud/developer/00_Overview.html

**Review by StushaaK — APPROVED** [review]

**Pull request merged**
